[package]
name = "redis_rocksdb"
version = "0.1.3"
edition = "2021"
authors = ["Peace <peacess@163.com>"]
exclude = [".gitignore"]
description = "rust implement structure kv(key/value) embedded database, storage by rocksdb"
repository = "https://github.com/selfopen/redis_rocksdb"
homepage = "https://github.com/selfopen/redis_rocksdb"
keywords = ["redis", "rocksdb", "nosql", "kv", "embedded"]
categories = ["database"]
license = "Apache-2.0"

[lib]
name = "redis_rocksdb"
path = "src/lib.rs"

[features]
default = ["u32"]
u32 = []

[dependencies]
log = "0.4.17"
anyhow = "1.0.58"
ckb-rocksdb = "0.18.1"

#rocksdb = { version = "0.18.0", features = ["multi-threaded-cf"] }
[dev-dependencies]
function_name = "0.3.0"
