#unstable_features = true
# Basic
hard_tabs = true
max_width = 160
use_small_heuristics = "Max"
# Imports
#imports_granularity = "Crate"
reorder_imports = true
#merge_imports = true
# Consistency
newline_style = "Unix"
# Format comments
comment_width = 160
#wrap_comments = true
# Misc
#spaces_around_ranges = false
#binop_separator = "Back"
#reorder_impl_items = true
#match_arm_leading_pipes = "Preserve"
#match_arm_blocks = true
match_block_trailing_comma = true
#trailing_comma = "Vertical"
#trailing_semicolon = true
use_field_init_shorthand = true